// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "packages/shared/prisma/schema.prisma",
  migrations: {
    path: "packages/shared/prisma/migrations",
    seed: "node packages/shared/prisma/seed.js",
  },
  datasource: {
    // Prisma 7 datasource URL source of truth for CLI + Client generation.
    url: process.env["DATABASE_URL"],
  },
});
